all:
  hosts:
    nfs:
      ansible_host: 172.31.42.73
      ansible_user: ec2-user
      ansible_ssh_private_key_file: Linux.pem
    web01:
      ansible_host: 16.170.224.10
      ansible_user: ec2-user
      ansible_ssh_private_key_file: Linux.pem
    web02:
      ansible_host: 172.31.46.80
      ansible_user: ec2-user
      ansible_ssh_private_key_file: Linux.pem
    db:
      ansible_host: 172.31.38.170
      ansible_user: ec2-user
      ansible_ssh_private_key_file: Linux.pem
    lb:
      ansible_host: 172.31.47.110
      ansible_user: ubuntu
      ansible_ssh_private_key_file: Linux.pem








